apiVersion: v1
kind: Service
metadata: 
  name: database
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata: 
  name: database
  labels:
    app: database
spec:
  containers:
  - name: database
    image: mysql:5.7.8
    ports: 
    - containerPort: 3306